var searchData=
[
  ['packet_20management_0',['packet management',['../group___group___endpoint_packet_management.html',1,'Endpoint Packet Management'],['../group___group___pipe_packet_management.html',1,'Pipe Packet Management']]],
  ['packet_20management_20avr8_1',['packet management avr8',['../group___group___endpoint_packet_management___a_v_r8.html',1,'Endpoint Packet Management (AVR8)'],['../group___group___pipe_packet_management___a_v_r8.html',1,'Pipe Packet Management (AVR8)']]],
  ['packet_20management_20uc3_2',['packet management uc3',['../group___group___endpoint_packet_management___u_c3.html',1,'Endpoint Packet Management (UC3)'],['../group___group___pipe_packet_management___u_c3.html',1,'Pipe Packet Management (UC3)']]],
  ['packet_20management_20xmega_3',['Endpoint Packet Management (XMEGA)',['../group___group___endpoint_packet_management___x_m_e_g_a.html',1,'']]],
  ['parser_4',['parser',['../group___group___config_descriptor_parser.html',1,'Configuration Descriptor Parser'],['../group___group___h_i_d_parser.html',1,'HID Report Parser']]],
  ['peripheral_20adc_20h_5',['ADC Driver - LUFA/Drivers/Peripheral/ADC.h',['../group___group___a_d_c.html',1,'']]],
  ['peripheral_20driver_20avr8_6',['peripheral driver avr8',['../group___group___a_d_c___a_v_r8.html',1,'ADC Peripheral Driver (AVR8)'],['../group___group___serial_s_p_i___a_v_r8.html',1,'Master SPI Mode Serial USART Peripheral Driver (AVR8)'],['../group___group___serial___a_v_r8.html',1,'Serial USART Peripheral Driver (AVR8)'],['../group___group___s_p_i___a_v_r8.html',1,'SPI Peripheral Driver (AVR8)'],['../group___group___t_w_i___a_v_r8.html',1,'TWI Peripheral Driver (AVR8)']]],
  ['peripheral_20driver_20xmega_7',['peripheral driver xmega',['../group___group___serial_s_p_i___x_m_e_g_a.html',1,'Master SPI Mode Serial USART Peripheral Driver (XMEGA)'],['../group___group___serial___x_m_e_g_a.html',1,'Serial USART Peripheral Driver (XMEGA)'],['../group___group___s_p_i___x_m_e_g_a.html',1,'SPI Peripheral Driver (XMEGA)'],['../group___group___t_w_i___x_m_e_g_a.html',1,'TWI Peripheral Driver (XMEGA)']]],
  ['peripheral_20drivers_8',['On-chip Peripheral Drivers',['../group___group___peripheral_drivers.html',1,'']]],
  ['peripheral_20serial_20h_9',['Serial USART Driver - LUFA/Drivers/Peripheral/Serial.h',['../group___group___serial.html',1,'']]],
  ['peripheral_20serialspi_20h_10',['Master SPI Mode Serial USART Driver - LUFA/Drivers/Peripheral/SerialSPI.h',['../group___group___serial_s_p_i.html',1,'']]],
  ['peripheral_20spi_20h_11',['SPI Driver - LUFA/Drivers/Peripheral/SPI.h',['../group___group___s_p_i.html',1,'']]],
  ['peripheral_20twi_20h_12',['TWI Driver - LUFA/Drivers/Peripheral/TWI.h',['../group___group___t_w_i.html',1,'']]],
  ['pipe_20control_20request_20management_13',['Pipe Control Request Management',['../group___group___pipe_control_req.html',1,'']]],
  ['pipe_20control_20request_20management_20avr8_14',['Pipe Control Request Management (AVR8)',['../group___group___pipe_control_req___a_v_r8.html',1,'']]],
  ['pipe_20control_20request_20management_20uc3_15',['Pipe Control Request Management (UC3)',['../group___group___pipe_control_req___u_c3.html',1,'']]],
  ['pipe_20data_20reading_20and_20writing_16',['Pipe Data Reading and Writing',['../group___group___pipe_r_w.html',1,'']]],
  ['pipe_20data_20reading_20and_20writing_20avr8_17',['Pipe Data Reading and Writing (AVR8)',['../group___group___pipe_r_w___a_v_r8.html',1,'']]],
  ['pipe_20data_20reading_20and_20writing_20uc3_18',['Pipe Data Reading and Writing (UC3)',['../group___group___pipe_r_w___u_c3.html',1,'']]],
  ['pipe_20management_19',['Pipe Management',['../group___group___pipe_management.html',1,'']]],
  ['pipe_20management_20avr8_20',['Pipe Management (AVR8)',['../group___group___pipe_management___a_v_r8.html',1,'']]],
  ['pipe_20management_20uc3_21',['Pipe Management (UC3)',['../group___group___pipe_management___u_c3.html',1,'']]],
  ['pipe_20packet_20management_22',['Pipe Packet Management',['../group___group___pipe_packet_management.html',1,'']]],
  ['pipe_20packet_20management_20avr8_23',['Pipe Packet Management (AVR8)',['../group___group___pipe_packet_management___a_v_r8.html',1,'']]],
  ['pipe_20packet_20management_20uc3_24',['Pipe Packet Management (UC3)',['../group___group___pipe_packet_management___u_c3.html',1,'']]],
  ['platform_20drivers_20lufa_20platform_20platform_20h_25',['System Platform Drivers - LUFA/Platform/Platform.h',['../group___group___platform_drivers.html',1,'']]],
  ['platform_20uc3_20clockmanagement_20h_26',['Clock Management Driver - LUFA/Platform/UC3/ClockManagement.h',['../group___group___platform_drivers___u_c3_clocks.html',1,'']]],
  ['platform_20uc3_20interruptmanagement_20h_27',['Interrupt Controller Driver - LUFA/Platform/UC3/InterruptManagement.h',['../group___group___platform_drivers___u_c3_interrupts.html',1,'']]],
  ['platform_20xmega_20clockmanagement_20h_28',['Clock Management Driver - LUFA/Platform/XMEGA/ClockManagement.h',['../group___group___platform_drivers___x_m_e_g_a_clocks.html',1,'']]],
  ['pololumicro_29',['POLOLUMICRO',['../group___group___board_info___p_o_l_o_l_u_m_i_c_r_o.html',1,'']]],
  ['primitive_20data_20types_30',['primitive data types',['../group___group___pipe_primitive_r_w.html',1,'Read/Write of Primitive Data Types'],['../group___group___endpoint_primitive_r_w.html',1,'Read/Write of Primitive Data Types']]],
  ['primitive_20data_20types_20avr8_31',['primitive data types avr8',['../group___group___pipe_primitive_r_w___a_v_r8.html',1,'Read/Write of Primitive Data Types (AVR8)'],['../group___group___endpoint_primitive_r_w___a_v_r8.html',1,'Read/Write of Primitive Data Types (AVR8)']]],
  ['primitive_20data_20types_20uc3_32',['primitive data types uc3',['../group___group___endpoint_primitive_r_w___u_c3.html',1,'Read/Write of Primitive Data Types (UC3)'],['../group___group___pipe_primitive_r_w___u_c3.html',1,'Read/Write of Primitive Data Types (UC3)']]],
  ['primitive_20data_20types_20xmega_33',['Read/Write of Primitive Data Types (XMEGA)',['../group___group___endpoint_primitive_r_w___x_m_e_g_a.html',1,'']]],
  ['printer_20class_20device_20mode_20driver_34',['Printer Class Device Mode Driver',['../group___group___u_s_b_class_printer_device.html',1,'']]],
  ['printer_20class_20driver_35',['Printer Class Driver',['../group___group___u_s_b_class_printer.html',1,'']]],
  ['printer_20class_20host_20mode_20driver_36',['Printer Class Host Mode Driver',['../group___group___u_s_b_class_printer_host.html',1,'']]]
];
