var searchData=
[
  ['sensor_20driver_20lufa_20drivers_20board_20temperature_20h_0',['Temperature Sensor Driver - LUFA/Drivers/Board/Temperature.h',['../group___group___temperature.html',1,'']]],
  ['serial_20class_20driver_1',['CDC-ACM (Virtual Serial) Class Driver',['../group___group___u_s_b_class_c_d_c.html',1,'']]],
  ['serial_20usart_20driver_20lufa_20drivers_20peripheral_20serial_20h_2',['Serial USART Driver - LUFA/Drivers/Peripheral/Serial.h',['../group___group___serial.html',1,'']]],
  ['serial_20usart_20driver_20lufa_20drivers_20peripheral_20serialspi_20h_3',['Master SPI Mode Serial USART Driver - LUFA/Drivers/Peripheral/SerialSPI.h',['../group___group___serial_s_p_i.html',1,'']]],
  ['serial_20usart_20peripheral_20driver_20avr8_4',['serial usart peripheral driver avr8',['../group___group___serial_s_p_i___a_v_r8.html',1,'Master SPI Mode Serial USART Peripheral Driver (AVR8)'],['../group___group___serial___a_v_r8.html',1,'Serial USART Peripheral Driver (AVR8)']]],
  ['serial_20usart_20peripheral_20driver_20xmega_5',['serial usart peripheral driver xmega',['../group___group___serial_s_p_i___x_m_e_g_a.html',1,'Master SPI Mode Serial USART Peripheral Driver (XMEGA)'],['../group___group___serial___x_m_e_g_a.html',1,'Serial USART Peripheral Driver (XMEGA)']]],
  ['serialspi_20h_6',['Master SPI Mode Serial USART Driver - LUFA/Drivers/Peripheral/SerialSPI.h',['../group___group___serial_s_p_i.html',1,'']]],
  ['sparkfun8u2_7',['sparkfun8u2',['../group___group___l_e_ds___s_p_a_r_k_f_u_n8_u2.html',1,'SPARKFUN8U2'],['../group___group___board_info___s_p_a_r_k_f_u_n8_u2.html',1,'SPARKFUN8U2']]],
  ['specific_20definitions_8',['specific definitions',['../group___group___architecture_specific.html',1,'Architecture Specific Definitions'],['../group___group___compiler_specific.html',1,'Compiler Specific Definitions']]],
  ['spi_20driver_20lufa_20drivers_20peripheral_20spi_20h_9',['SPI Driver - LUFA/Drivers/Peripheral/SPI.h',['../group___group___s_p_i.html',1,'']]],
  ['spi_20mode_20serial_20usart_20driver_20lufa_20drivers_20peripheral_20serialspi_20h_10',['Master SPI Mode Serial USART Driver - LUFA/Drivers/Peripheral/SerialSPI.h',['../group___group___serial_s_p_i.html',1,'']]],
  ['spi_20mode_20serial_20usart_20peripheral_20driver_20avr8_11',['Master SPI Mode Serial USART Peripheral Driver (AVR8)',['../group___group___serial_s_p_i___a_v_r8.html',1,'']]],
  ['spi_20mode_20serial_20usart_20peripheral_20driver_20xmega_12',['Master SPI Mode Serial USART Peripheral Driver (XMEGA)',['../group___group___serial_s_p_i___x_m_e_g_a.html',1,'']]],
  ['spi_20peripheral_20driver_20avr8_13',['SPI Peripheral Driver (AVR8)',['../group___group___s_p_i___a_v_r8.html',1,'']]],
  ['spi_20peripheral_20driver_20xmega_14',['SPI Peripheral Driver (XMEGA)',['../group___group___s_p_i___x_m_e_g_a.html',1,'']]],
  ['standard_20usb_20requests_15',['Standard USB Requests',['../group___group___std_request.html',1,'']]],
  ['stange_5fisp_16',['stange_isp',['../group___group___board_info___s_t_a_n_g_e___i_s_p.html',1,'STANGE_ISP'],['../group___group___l_e_ds___s_t_a_n_g_e___i_s_p.html',1,'STANGE_ISP'],['../group___group___buttons___s_t_a_n_g_e___i_s_p.html',1,'STANGE_ISP']]],
  ['still_20image_20class_20driver_17',['Still Image Class Driver',['../group___group___u_s_b_class_s_i.html',1,'']]],
  ['still_20image_20class_20host_20mode_20driver_18',['Still Image Class Host Mode Driver',['../group___group___u_s_b_class_still_image_host.html',1,'']]],
  ['stk525_19',['stk525',['../group___group___board_info___s_t_k525.html',1,'STK525'],['../group___group___buttons___s_t_k525.html',1,'STK525'],['../group___group___dataflash___s_t_k525.html',1,'STK525'],['../group___group___joystick___s_t_k525.html',1,'STK525'],['../group___group___l_e_ds___s_t_k525.html',1,'STK525']]],
  ['stk526_20',['stk526',['../group___group___dataflash___s_t_k526.html',1,'STK526'],['../group___group___buttons___s_t_k526.html',1,'STK526'],['../group___group___board_info___s_t_k526.html',1,'STK526'],['../group___group___l_e_ds___s_t_k526.html',1,'STK526'],['../group___group___joystick___s_t_k526.html',1,'STK526']]],
  ['storage_20class_20device_20mode_20driver_21',['Mass Storage Class Device Mode Driver',['../group___group___u_s_b_class_m_s_device.html',1,'']]],
  ['storage_20class_20driver_22',['Mass Storage Class Driver',['../group___group___u_s_b_class_m_s.html',1,'']]],
  ['storage_20class_20host_20mode_20driver_23',['Mass Storage Class Host Mode Driver',['../group___group___u_s_b_class_mass_storage_host.html',1,'']]],
  ['streams_24',['streams',['../group___group___pipe_stream_r_w.html',1,'Read/Write of Multi-Byte Streams'],['../group___group___endpoint_stream_r_w.html',1,'Read/Write of Multi-Byte Streams']]],
  ['streams_20avr8_25',['streams avr8',['../group___group___endpoint_stream_r_w___a_v_r8.html',1,'Read/Write of Multi-Byte Streams (AVR8)'],['../group___group___pipe_stream_r_w___a_v_r8.html',1,'Read/Write of Multi-Byte Streams (AVR8)']]],
  ['streams_20uc3_26',['streams uc3',['../group___group___pipe_stream_r_w___u_c3.html',1,'Read/Write of Multi-Byte Streams (UC3)'],['../group___group___endpoint_stream_r_w___u_c3.html',1,'Read/Write of Multi-Byte Streams (UC3)']]],
  ['streams_20xmega_27',['Read/Write of Multi-Byte Streams (XMEGA)',['../group___group___endpoint_stream_r_w___x_m_e_g_a.html',1,'']]],
  ['system_20platform_20drivers_20lufa_20platform_20platform_20h_28',['System Platform Drivers - LUFA/Platform/Platform.h',['../group___group___platform_drivers.html',1,'']]]
];
